name: Second Workflow

on: issues

jobs:
  Output_event_details:
    runs-on: ubuntu latest
    steps:
      - name: Output details
        run: echo "${{ toJSON(github.event) }}"
      - run: echo "${{ github.event_name }}"
